### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by AllaSydoriak** [komarnitskyi/theme-zephyr#7]
I want to see time that my command took to complete)

**Comment by serhiiboreiko** [comment]
NO PROBLEM.

REDIRECTING THIS ISSUE TO MAXIM....... @maxkharena

**Comment by serhiiboreiko** [comment]
@AllaSydoriak Please, run this command to see and use the new feature
```fish
omf update zephyr
```

This is how it looks like
![image](https://user-images.githubusercontent.com/11788629/43314674-4faf0336-919c-11e8-8eb1-e0e54878557e.png)

**Comment by komarnitskyi** [comment]
resolved
